### ISSUE TITLE
Нарушение презентации.

### ISSUE THREAD

**Issue by SteadyCoder** [shadeturnip/TestTask#1]
Вот это приводит к не очень хорошему поведению. Лучше сначала удалять вью, а потом презентовать, делать в async. У меня разок вылезло, типа Алерт появился не в тему. 

https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/MapViewController%20.swift#L85

А вообще activity indicator на весь экран, лучше делать контролером, если презентуется на весь экран, потому что рано или поздно стыкнешься с проблемами. Скажу по опыту. Плюс намного легче переиспользовать.

**Comment by shadeturnip** [comment]
Воспроизвёл и исправил. Нехорошее поведение уже проявлялось, оно описано вами в issue #2
