### ISSUE TITLE
Черный экран.

### ISSUE THREAD

**Issue by SteadyCoder** [shadeturnip/TestTask#2]
Случилось , когда кнопка поиск, была нажата с клавиатуры, но сам момент SearchBar оставался активным. При этом состоянии перешел на другую табу, вернулся получился черный экран.
![image 2019-02-28 22 31 56](https://user-images.githubusercontent.com/10299334/53596560-a9c03000-3ba8-11e9-926c-f83962963086.jpg)

<img width="1280" alt="screen shot 2019-02-28 at 10 16 48 pm" src="https://user-images.githubusercontent.com/10299334/53596567-af1d7a80-3ba8-11e9-9eb2-971f4bf5f5cc.png">

**Comment by shadeturnip** [comment]
Это возникало по причине нарушения презентации. Search controller должен был быть скрыт при переходе на новую вкладку tabBar.

**Comment by SteadyCoder** [comment]
хах, я понимаю это )) это я скинул , чтобы ты пофиксил
