### ISSUE TITLE
Обсуждение VenuesTableViewController

### ISSUE THREAD

**Issue by SteadyCoder** [shadeturnip/TestTask#3]
Не очень понимаю зачем это дефолтное значение здесь. Лучше делать optional !, ведь ты все равно потом делаешь проверку. Либо в 96 добавлять default value
https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/VenuesTableViewController.swift#L91

Лучше сделать enum, хоть и придется rawValue вызывать.
https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/VenuesTableViewController.swift#L130

На будущее есть прочерти , что-то типа hidesWhenStopped
https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/VenuesTableViewController.swift#L103

Тут нужен else case в котором ставится nil. Либо перед if ставить nil image.
На будущее есть прочерти , что-то типа hidesWhenStopped
https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/VenuesTableViewController.swift#L105

Лучше энкапсулировать.
https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/VenuesTableViewController.swift#L126 

Почему вызывается во viewDidAppear?
https://github.com/shadeturnip/TestTask/blob/66623c14b25e0b4584db056664f2de9ef57c0227/TestTask/Controller/VenuesTableViewController.swift#L27

**Comment by shadeturnip** [comment]
При использовании 

> optional ! 

требуется инициализировать объект перед обращением, потому там было указано значение по-умолчанию. 
Когда-то я столкнулся с некорректным поведением свойства hidesWhenStopped, это было осмысленное решение. Сейчас всё хорошо. 

Вызов getRecommendation в методе viewDidAppear использовался как проверочный, забыл удалить его перед отправкой. 
` override func viewDidAppear(_ animated: Bool) {
        if results.count == 0 {
            self.getRecommendation()
        }
    }`

**Comment by SteadyCoder** [comment]
а зачем тебе использовать такой optional "!"  ?

**Comment by shadeturnip** [comment]
Дело в том что незачем, в таком случаи лучше создать опционал как ?. Я использовал цитирование чтобы ответить.

**Comment by SteadyCoder** [comment]
понял
